name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: 
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Updated version of the action
      - name: Copy blogs to public/blog
        run: |
          mkdir -p public/blog
          cp -rf blogs/* public/blog
      - name: Run gen_blog_list script
        run: bash ./gen_blog_list.sh
      - uses: actions/setup-node@master
      - run: npm install
      - run: pwd
      - run: npm run build
        working-directory: .
      - run: ls -la
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Updated version of the action
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./dist # Specify the directory to deploy
